# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-01 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('ip', models.CharField(max_length=64, unique=True)),
                ('link', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('port', models.IntegerField()),
                ('position', models.CharField(max_length=64)),
                ('introduce', models.CharField(max_length=256)),
                ('state', models.BooleanField(default=False)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.group')),
            ],
        ),
    ]
